package com.major.commons.util;

import java.util.Date;
import java.util.TimeZone;

/**
 * User: Minjie
 * Date: 13-10-31
 * Time: 下午9:34
 */
@SuppressWarnings("UnusedDeclaration")
public class TimeZoneUtil {
    public static final TimeZone ACT = TimeZone.getTimeZone("ACT"); //中央标准时间（北领地）
    public static final TimeZone AET = TimeZone.getTimeZone("AET"); //东部标准时间（新南威尔斯）
    public static final TimeZone Africa_Abidjan = TimeZone.getTimeZone("Africa/Abidjan"); //格林威治时间
    public static final TimeZone Africa_Accra = TimeZone.getTimeZone("Africa/Accra"); //加纳时间
    public static final TimeZone Africa_Addis_Ababa = TimeZone.getTimeZone("Africa/Addis_Ababa"); //东非时间
    public static final TimeZone Africa_Algiers = TimeZone.getTimeZone("Africa/Algiers"); //中欧时间
    public static final TimeZone Africa_Asmara = TimeZone.getTimeZone("Africa/Asmara"); //东非时间
    public static final TimeZone Africa_Asmera = TimeZone.getTimeZone("Africa/Asmera"); //东非时间
    public static final TimeZone Africa_Bamako = TimeZone.getTimeZone("Africa/Bamako"); //格林威治时间
    public static final TimeZone Africa_Bangui = TimeZone.getTimeZone("Africa/Bangui"); //西非时间
    public static final TimeZone Africa_Banjul = TimeZone.getTimeZone("Africa/Banjul"); //格林威治时间
    public static final TimeZone Africa_Bissau = TimeZone.getTimeZone("Africa/Bissau"); //格林威治时间
    public static final TimeZone Africa_Blantyre = TimeZone.getTimeZone("Africa/Blantyre"); //中非时间
    public static final TimeZone Africa_Brazzaville = TimeZone.getTimeZone("Africa/Brazzaville"); //西非时间
    public static final TimeZone Africa_Bujumbura = TimeZone.getTimeZone("Africa/Bujumbura"); //中非时间
    public static final TimeZone Africa_Cairo = TimeZone.getTimeZone("Africa/Cairo"); //东欧时间
    public static final TimeZone Africa_Casablanca = TimeZone.getTimeZone("Africa/Casablanca"); //西欧时间
    public static final TimeZone Africa_Ceuta = TimeZone.getTimeZone("Africa/Ceuta"); //中欧时间
    public static final TimeZone Africa_Conakry = TimeZone.getTimeZone("Africa/Conakry"); //格林威治时间
    public static final TimeZone Africa_Dakar = TimeZone.getTimeZone("Africa/Dakar"); //格林威治时间
    public static final TimeZone Africa_Dar_es_Salaam = TimeZone.getTimeZone("Africa/Dar_es_Salaam"); //东非时间
    public static final TimeZone Africa_Djibouti = TimeZone.getTimeZone("Africa/Djibouti"); //东非时间
    public static final TimeZone Africa_Douala = TimeZone.getTimeZone("Africa/Douala"); //西非时间
    public static final TimeZone Africa_El_Aaiun = TimeZone.getTimeZone("Africa/El_Aaiun"); //西欧时间
    public static final TimeZone Africa_Freetown = TimeZone.getTimeZone("Africa/Freetown"); //格林威治时间
    public static final TimeZone Africa_Gaborone = TimeZone.getTimeZone("Africa/Gaborone"); //中非时间
    public static final TimeZone Africa_Harare = TimeZone.getTimeZone("Africa/Harare"); //中非时间
    public static final TimeZone Africa_Johannesburg = TimeZone.getTimeZone("Africa/Johannesburg"); //南非标准时间
    public static final TimeZone Africa_Juba = TimeZone.getTimeZone("Africa/Juba"); //东非时间
    public static final TimeZone Africa_Kampala = TimeZone.getTimeZone("Africa/Kampala"); //东非时间
    public static final TimeZone Africa_Khartoum = TimeZone.getTimeZone("Africa/Khartoum"); //东非时间
    public static final TimeZone Africa_Kigali = TimeZone.getTimeZone("Africa/Kigali"); //中非时间
    public static final TimeZone Africa_Kinshasa = TimeZone.getTimeZone("Africa/Kinshasa"); //西非时间
    public static final TimeZone Africa_Lagos = TimeZone.getTimeZone("Africa/Lagos"); //西非时间
    public static final TimeZone Africa_Libreville = TimeZone.getTimeZone("Africa/Libreville"); //西非时间
    public static final TimeZone Africa_Lome = TimeZone.getTimeZone("Africa/Lome"); //格林威治时间
    public static final TimeZone Africa_Luanda = TimeZone.getTimeZone("Africa/Luanda"); //西非时间
    public static final TimeZone Africa_Lubumbashi = TimeZone.getTimeZone("Africa/Lubumbashi"); //中非时间
    public static final TimeZone Africa_Lusaka = TimeZone.getTimeZone("Africa/Lusaka"); //中非时间
    public static final TimeZone Africa_Malabo = TimeZone.getTimeZone("Africa/Malabo"); //西非时间
    public static final TimeZone Africa_Maputo = TimeZone.getTimeZone("Africa/Maputo"); //中非时间
    public static final TimeZone Africa_Maseru = TimeZone.getTimeZone("Africa/Maseru"); //南非标准时间
    public static final TimeZone Africa_Mbabane = TimeZone.getTimeZone("Africa/Mbabane"); //南非标准时间
    public static final TimeZone Africa_Mogadishu = TimeZone.getTimeZone("Africa/Mogadishu"); //东非时间
    public static final TimeZone Africa_Monrovia = TimeZone.getTimeZone("Africa/Monrovia"); //格林威治时间
    public static final TimeZone Africa_Nairobi = TimeZone.getTimeZone("Africa/Nairobi"); //东非时间
    public static final TimeZone Africa_Ndjamena = TimeZone.getTimeZone("Africa/Ndjamena"); //西非时间
    public static final TimeZone Africa_Niamey = TimeZone.getTimeZone("Africa/Niamey"); //西非时间
    public static final TimeZone Africa_Nouakchott = TimeZone.getTimeZone("Africa/Nouakchott"); //格林威治时间
    public static final TimeZone Africa_Ouagadougou = TimeZone.getTimeZone("Africa/Ouagadougou"); //格林威治时间
    public static final TimeZone Africa_Porto_Novo = TimeZone.getTimeZone("Africa/Porto-Novo"); //西非时间
    public static final TimeZone Africa_Sao_Tome = TimeZone.getTimeZone("Africa/Sao_Tome"); //格林威治时间
    public static final TimeZone Africa_Timbuktu = TimeZone.getTimeZone("Africa/Timbuktu"); //格林威治时间
    public static final TimeZone Africa_Tripoli = TimeZone.getTimeZone("Africa/Tripoli"); //东欧时间
    public static final TimeZone Africa_Tunis = TimeZone.getTimeZone("Africa/Tunis"); //中欧时间
    public static final TimeZone Africa_Windhoek = TimeZone.getTimeZone("Africa/Windhoek"); //西非时间
    public static final TimeZone AGT = TimeZone.getTimeZone("AGT"); //阿根廷时间
    public static final TimeZone America_Adak = TimeZone.getTimeZone("America/Adak"); //夏威夷-阿留申群岛标准时间
    public static final TimeZone America_Anchorage = TimeZone.getTimeZone("America/Anchorage"); //阿拉斯加标准时间
    public static final TimeZone America_Anguilla = TimeZone.getTimeZone("America/Anguilla"); //大西洋标准时间
    public static final TimeZone America_Antigua = TimeZone.getTimeZone("America/Antigua"); //大西洋标准时间
    public static final TimeZone America_Araguaina = TimeZone.getTimeZone("America/Araguaina"); //巴西利亚时间
    public static final TimeZone America_Argentina_Buenos_Aires = TimeZone.getTimeZone("America/Argentina/Buenos_Aires"); //阿根廷时间
    public static final TimeZone America_Argentina_Catamarca = TimeZone.getTimeZone("America/Argentina/Catamarca"); //阿根廷时间
    public static final TimeZone America_Argentina_ComodRivadavia = TimeZone.getTimeZone("America/Argentina/ComodRivadavia"); //阿根廷时间
    public static final TimeZone America_Argentina_Cordoba = TimeZone.getTimeZone("America/Argentina/Cordoba"); //阿根廷时间
    public static final TimeZone America_Argentina_Jujuy = TimeZone.getTimeZone("America/Argentina/Jujuy"); //阿根廷时间
    public static final TimeZone America_Argentina_La_Rioja = TimeZone.getTimeZone("America/Argentina/La_Rioja"); //阿根廷时间
    public static final TimeZone America_Argentina_Mendoza = TimeZone.getTimeZone("America/Argentina/Mendoza"); //阿根廷时间
    public static final TimeZone America_Argentina_Rio_Gallegos = TimeZone.getTimeZone("America/Argentina/Rio_Gallegos"); //阿根廷时间
    public static final TimeZone America_Argentina_Salta = TimeZone.getTimeZone("America/Argentina/Salta"); //阿根廷时间
    public static final TimeZone America_Argentina_San_Juan = TimeZone.getTimeZone("America/Argentina/San_Juan"); //阿根廷时间
    public static final TimeZone America_Argentina_San_Luis = TimeZone.getTimeZone("America/Argentina/San_Luis"); //西阿根廷时间
    public static final TimeZone America_Argentina_Tucuman = TimeZone.getTimeZone("America/Argentina/Tucuman"); //阿根廷时间
    public static final TimeZone America_Argentina_Ushuaia = TimeZone.getTimeZone("America/Argentina/Ushuaia"); //阿根廷时间
    public static final TimeZone America_Aruba = TimeZone.getTimeZone("America/Aruba"); //大西洋标准时间
    public static final TimeZone America_Asuncion = TimeZone.getTimeZone("America/Asuncion"); //巴拉圭时间
    public static final TimeZone America_Atikokan = TimeZone.getTimeZone("America/Atikokan"); //东部标准时间
    public static final TimeZone America_Atka = TimeZone.getTimeZone("America/Atka"); //夏威夷-阿留申群岛标准时间
    public static final TimeZone America_Bahia = TimeZone.getTimeZone("America/Bahia"); //巴西利亚时间
    public static final TimeZone America_Bahia_Banderas = TimeZone.getTimeZone("America/Bahia_Banderas"); //中央标准时间
    public static final TimeZone America_Barbados = TimeZone.getTimeZone("America/Barbados"); //大西洋标准时间
    public static final TimeZone America_Belem = TimeZone.getTimeZone("America/Belem"); //巴西利亚时间
    public static final TimeZone America_Belize = TimeZone.getTimeZone("America/Belize"); //中央标准时间
    public static final TimeZone America_Blanc_Sablon = TimeZone.getTimeZone("America/Blanc-Sablon"); //大西洋标准时间
    public static final TimeZone America_Boa_Vista = TimeZone.getTimeZone("America/Boa_Vista"); //亚马逊时间
    public static final TimeZone America_Bogota = TimeZone.getTimeZone("America/Bogota"); //哥伦比亚时间
    public static final TimeZone America_Boise = TimeZone.getTimeZone("America/Boise"); //Mountain 标准时间
    public static final TimeZone America_Buenos_Aires = TimeZone.getTimeZone("America/Buenos_Aires"); //阿根廷时间
    public static final TimeZone America_Cambridge_Bay = TimeZone.getTimeZone("America/Cambridge_Bay"); //Mountain 标准时间
    public static final TimeZone America_Campo_Grande = TimeZone.getTimeZone("America/Campo_Grande"); //亚马逊时间
    public static final TimeZone America_Cancun = TimeZone.getTimeZone("America/Cancun"); //中央标准时间
    public static final TimeZone America_Caracas = TimeZone.getTimeZone("America/Caracas"); //委内瑞拉时间
    public static final TimeZone America_Catamarca = TimeZone.getTimeZone("America/Catamarca"); //阿根廷时间
    public static final TimeZone America_Cayenne = TimeZone.getTimeZone("America/Cayenne"); //法属圭亚那时间
    public static final TimeZone America_Cayman = TimeZone.getTimeZone("America/Cayman"); //东部标准时间
    public static final TimeZone America_Chicago = TimeZone.getTimeZone("America/Chicago"); //中央标准时间
    public static final TimeZone America_Chihuahua = TimeZone.getTimeZone("America/Chihuahua"); //Mountain 标准时间
    public static final TimeZone America_Coral_Harbour = TimeZone.getTimeZone("America/Coral_Harbour"); //东部标准时间
    public static final TimeZone America_Cordoba = TimeZone.getTimeZone("America/Cordoba"); //阿根廷时间
    public static final TimeZone America_Costa_Rica = TimeZone.getTimeZone("America/Costa_Rica"); //中央标准时间
    public static final TimeZone America_Creston = TimeZone.getTimeZone("America/Creston"); //Mountain 标准时间
    public static final TimeZone America_Cuiaba = TimeZone.getTimeZone("America/Cuiaba"); //亚马逊时间
    public static final TimeZone America_Curacao = TimeZone.getTimeZone("America/Curacao"); //大西洋标准时间
    public static final TimeZone America_Danmarkshavn = TimeZone.getTimeZone("America/Danmarkshavn"); //格林威治时间
    public static final TimeZone America_Dawson = TimeZone.getTimeZone("America/Dawson"); //太平洋标准时间
    public static final TimeZone America_Dawson_Creek = TimeZone.getTimeZone("America/Dawson_Creek"); //Mountain 标准时间
    public static final TimeZone America_Denver = TimeZone.getTimeZone("America/Denver"); //Mountain 标准时间
    public static final TimeZone America_Detroit = TimeZone.getTimeZone("America/Detroit"); //东部标准时间
    public static final TimeZone America_Dominica = TimeZone.getTimeZone("America/Dominica"); //大西洋标准时间
    public static final TimeZone America_Edmonton = TimeZone.getTimeZone("America/Edmonton"); //Mountain 标准时间
    public static final TimeZone America_Eirunepe = TimeZone.getTimeZone("America/Eirunepe"); //亚马逊时间
    public static final TimeZone America_El_Salvador = TimeZone.getTimeZone("America/El_Salvador"); //中央标准时间
    public static final TimeZone America_Ensenada = TimeZone.getTimeZone("America/Ensenada"); //太平洋标准时间
    public static final TimeZone America_Fort_Wayne = TimeZone.getTimeZone("America/Fort_Wayne"); //东部标准时间
    public static final TimeZone America_Fortaleza = TimeZone.getTimeZone("America/Fortaleza"); //巴西利亚时间
    public static final TimeZone America_Glace_Bay = TimeZone.getTimeZone("America/Glace_Bay"); //大西洋标准时间
    public static final TimeZone America_Godthab = TimeZone.getTimeZone("America/Godthab"); //西格林兰岛时间
    public static final TimeZone America_Goose_Bay = TimeZone.getTimeZone("America/Goose_Bay"); //大西洋标准时间
    public static final TimeZone America_Grand_Turk = TimeZone.getTimeZone("America/Grand_Turk"); //东部标准时间
    public static final TimeZone America_Grenada = TimeZone.getTimeZone("America/Grenada"); //大西洋标准时间
    public static final TimeZone America_Guadeloupe = TimeZone.getTimeZone("America/Guadeloupe"); //大西洋标准时间
    public static final TimeZone America_Guatemala = TimeZone.getTimeZone("America/Guatemala"); //中央标准时间
    public static final TimeZone America_Guayaquil = TimeZone.getTimeZone("America/Guayaquil"); //厄瓜多尔时间
    public static final TimeZone America_Guyana = TimeZone.getTimeZone("America/Guyana"); //圭亚那时间
    public static final TimeZone America_Halifax = TimeZone.getTimeZone("America/Halifax"); //大西洋标准时间
    public static final TimeZone America_Havana = TimeZone.getTimeZone("America/Havana"); //古巴标准时间
    public static final TimeZone America_Hermosillo = TimeZone.getTimeZone("America/Hermosillo"); //Mountain 标准时间
    public static final TimeZone America_Indiana_Indianapolis = TimeZone.getTimeZone("America/Indiana/Indianapolis"); //东部标准时间
    public static final TimeZone America_Indiana_Knox = TimeZone.getTimeZone("America/Indiana/Knox"); //中央标准时间
    public static final TimeZone America_Indiana_Marengo = TimeZone.getTimeZone("America/Indiana/Marengo"); //东部标准时间
    public static final TimeZone America_Indiana_Petersburg = TimeZone.getTimeZone("America/Indiana/Petersburg"); //东部标准时间
    public static final TimeZone America_Indiana_Tell_City = TimeZone.getTimeZone("America/Indiana/Tell_City"); //中央标准时间
    public static final TimeZone America_Indiana_Vevay = TimeZone.getTimeZone("America/Indiana/Vevay"); //东部标准时间
    public static final TimeZone America_Indiana_Vincennes = TimeZone.getTimeZone("America/Indiana/Vincennes"); //东部标准时间
    public static final TimeZone America_Indiana_Winamac = TimeZone.getTimeZone("America/Indiana/Winamac"); //东部标准时间
    public static final TimeZone America_Indianapolis = TimeZone.getTimeZone("America/Indianapolis"); //东部标准时间
    public static final TimeZone America_Inuvik = TimeZone.getTimeZone("America/Inuvik"); //Mountain 标准时间
    public static final TimeZone America_Iqaluit = TimeZone.getTimeZone("America/Iqaluit"); //东部标准时间
    public static final TimeZone America_Jamaica = TimeZone.getTimeZone("America/Jamaica"); //东部标准时间
    public static final TimeZone America_Jujuy = TimeZone.getTimeZone("America/Jujuy"); //阿根廷时间
    public static final TimeZone America_Juneau = TimeZone.getTimeZone("America/Juneau"); //阿拉斯加标准时间
    public static final TimeZone America_Kentucky_Louisville = TimeZone.getTimeZone("America/Kentucky/Louisville"); //东部标准时间
    public static final TimeZone America_Kentucky_Monticello = TimeZone.getTimeZone("America/Kentucky/Monticello"); //东部标准时间
    public static final TimeZone America_Knox_IN = TimeZone.getTimeZone("America/Knox_IN"); //中央标准时间
    public static final TimeZone America_Kralendijk = TimeZone.getTimeZone("America/Kralendijk"); //大西洋标准时间
    public static final TimeZone America_La_Paz = TimeZone.getTimeZone("America/La_Paz"); //玻利维亚时间
    public static final TimeZone America_Lima = TimeZone.getTimeZone("America/Lima"); //秘鲁时间
    public static final TimeZone America_Los_Angeles = TimeZone.getTimeZone("America/Los_Angeles"); //太平洋标准时间
    public static final TimeZone America_Louisville = TimeZone.getTimeZone("America/Louisville"); //东部标准时间
    public static final TimeZone America_Lower_Princes = TimeZone.getTimeZone("America/Lower_Princes"); //大西洋标准时间
    public static final TimeZone America_Maceio = TimeZone.getTimeZone("America/Maceio"); //巴西利亚时间
    public static final TimeZone America_Managua = TimeZone.getTimeZone("America/Managua"); //中央标准时间
    public static final TimeZone America_Manaus = TimeZone.getTimeZone("America/Manaus"); //亚马逊时间
    public static final TimeZone America_Marigot = TimeZone.getTimeZone("America/Marigot"); //大西洋标准时间
    public static final TimeZone America_Martinique = TimeZone.getTimeZone("America/Martinique"); //大西洋标准时间
    public static final TimeZone America_Matamoros = TimeZone.getTimeZone("America/Matamoros"); //中央标准时间
    public static final TimeZone America_Mazatlan = TimeZone.getTimeZone("America/Mazatlan"); //Mountain 标准时间
    public static final TimeZone America_Mendoza = TimeZone.getTimeZone("America/Mendoza"); //阿根廷时间
    public static final TimeZone America_Menominee = TimeZone.getTimeZone("America/Menominee"); //中央标准时间
    public static final TimeZone America_Merida = TimeZone.getTimeZone("America/Merida"); //中央标准时间
    public static final TimeZone America_Metlakatla = TimeZone.getTimeZone("America/Metlakatla"); //Metlakatla Standard Time
    public static final TimeZone America_Mexico_City = TimeZone.getTimeZone("America/Mexico_City"); //中央标准时间
    public static final TimeZone America_Miquelon = TimeZone.getTimeZone("America/Miquelon"); //皮埃尔岛及密克隆岛标准时间
    public static final TimeZone America_Moncton = TimeZone.getTimeZone("America/Moncton"); //大西洋标准时间
    public static final TimeZone America_Monterrey = TimeZone.getTimeZone("America/Monterrey"); //中央标准时间
    public static final TimeZone America_Montevideo = TimeZone.getTimeZone("America/Montevideo"); //乌拉圭时间
    public static final TimeZone America_Montreal = TimeZone.getTimeZone("America/Montreal"); //东部标准时间
    public static final TimeZone America_Montserrat = TimeZone.getTimeZone("America/Montserrat"); //大西洋标准时间
    public static final TimeZone America_Nassau = TimeZone.getTimeZone("America/Nassau"); //东部标准时间
    public static final TimeZone America_New_York = TimeZone.getTimeZone("America/New_York"); //东部标准时间
    public static final TimeZone America_Nipigon = TimeZone.getTimeZone("America/Nipigon"); //东部标准时间
    public static final TimeZone America_Nome = TimeZone.getTimeZone("America/Nome"); //阿拉斯加标准时间
    public static final TimeZone America_Noronha = TimeZone.getTimeZone("America/Noronha"); //费尔南多德诺罗尼亚时间
    public static final TimeZone America_North_Dakota_Beulah = TimeZone.getTimeZone("America/North_Dakota/Beulah"); //中央标准时间
    public static final TimeZone America_North_Dakota_Center = TimeZone.getTimeZone("America/North_Dakota/Center"); //中央标准时间
    public static final TimeZone America_North_Dakota_New_Salem = TimeZone.getTimeZone("America/North_Dakota/New_Salem"); //中央标准时间
    public static final TimeZone America_Ojinaga = TimeZone.getTimeZone("America/Ojinaga"); //Mountain 标准时间
    public static final TimeZone America_Panama = TimeZone.getTimeZone("America/Panama"); //东部标准时间
    public static final TimeZone America_Pangnirtung = TimeZone.getTimeZone("America/Pangnirtung"); //东部标准时间
    public static final TimeZone America_Paramaribo = TimeZone.getTimeZone("America/Paramaribo"); //苏利南时间
    public static final TimeZone America_Phoenix = TimeZone.getTimeZone("America/Phoenix"); //Mountain 标准时间
    public static final TimeZone America_Port_au_Prince = TimeZone.getTimeZone("America/Port-au-Prince"); //东部标准时间
    public static final TimeZone America_Port_of_Spain = TimeZone.getTimeZone("America/Port_of_Spain"); //大西洋标准时间
    public static final TimeZone America_Porto_Acre = TimeZone.getTimeZone("America/Porto_Acre"); //亚马逊时间
    public static final TimeZone America_Porto_Velho = TimeZone.getTimeZone("America/Porto_Velho"); //亚马逊时间
    public static final TimeZone America_Puerto_Rico = TimeZone.getTimeZone("America/Puerto_Rico"); //大西洋标准时间
    public static final TimeZone America_Rainy_River = TimeZone.getTimeZone("America/Rainy_River"); //中央标准时间
    public static final TimeZone America_Rankin_Inlet = TimeZone.getTimeZone("America/Rankin_Inlet"); //中央标准时间
    public static final TimeZone America_Recife = TimeZone.getTimeZone("America/Recife"); //巴西利亚时间
    public static final TimeZone America_Regina = TimeZone.getTimeZone("America/Regina"); //中央标准时间
    public static final TimeZone America_Resolute = TimeZone.getTimeZone("America/Resolute"); //中央标准时间
    public static final TimeZone America_Rio_Branco = TimeZone.getTimeZone("America/Rio_Branco"); //亚马逊时间
    public static final TimeZone America_Rosario = TimeZone.getTimeZone("America/Rosario"); //阿根廷时间
    public static final TimeZone America_Santa_Isabel = TimeZone.getTimeZone("America/Santa_Isabel"); //太平洋标准时间
    public static final TimeZone America_Santarem = TimeZone.getTimeZone("America/Santarem"); //巴西利亚时间
    public static final TimeZone America_Santiago = TimeZone.getTimeZone("America/Santiago"); //智利时间
    public static final TimeZone America_Santo_Domingo = TimeZone.getTimeZone("America/Santo_Domingo"); //大西洋标准时间
    public static final TimeZone America_Sao_Paulo = TimeZone.getTimeZone("America/Sao_Paulo"); //巴西利亚时间
    public static final TimeZone America_Scoresbysund = TimeZone.getTimeZone("America/Scoresbysund"); //东格林岛时间
    public static final TimeZone America_Shiprock = TimeZone.getTimeZone("America/Shiprock"); //Mountain 标准时间
    public static final TimeZone America_Sitka = TimeZone.getTimeZone("America/Sitka"); //阿拉斯加标准时间
    public static final TimeZone America_St_Barthelemy = TimeZone.getTimeZone("America/St_Barthelemy"); //大西洋标准时间
    public static final TimeZone America_St_Johns = TimeZone.getTimeZone("America/St_Johns"); //纽芬兰标准时间
    public static final TimeZone America_St_Kitts = TimeZone.getTimeZone("America/St_Kitts"); //大西洋标准时间
    public static final TimeZone America_St_Lucia = TimeZone.getTimeZone("America/St_Lucia"); //大西洋标准时间
    public static final TimeZone America_St_Thomas = TimeZone.getTimeZone("America/St_Thomas"); //大西洋标准时间
    public static final TimeZone America_St_Vincent = TimeZone.getTimeZone("America/St_Vincent"); //大西洋标准时间
    public static final TimeZone America_Swift_Current = TimeZone.getTimeZone("America/Swift_Current"); //中央标准时间
    public static final TimeZone America_Tegucigalpa = TimeZone.getTimeZone("America/Tegucigalpa"); //中央标准时间
    public static final TimeZone America_Thule = TimeZone.getTimeZone("America/Thule"); //大西洋标准时间
    public static final TimeZone America_Thunder_Bay = TimeZone.getTimeZone("America/Thunder_Bay"); //东部标准时间
    public static final TimeZone America_Tijuana = TimeZone.getTimeZone("America/Tijuana"); //太平洋标准时间
    public static final TimeZone America_Toronto = TimeZone.getTimeZone("America/Toronto"); //东部标准时间
    public static final TimeZone America_Tortola = TimeZone.getTimeZone("America/Tortola"); //大西洋标准时间
    public static final TimeZone America_Vancouver = TimeZone.getTimeZone("America/Vancouver"); //太平洋标准时间
    public static final TimeZone America_Virgin = TimeZone.getTimeZone("America/Virgin"); //大西洋标准时间
    public static final TimeZone America_Whitehorse = TimeZone.getTimeZone("America/Whitehorse"); //太平洋标准时间
    public static final TimeZone America_Winnipeg = TimeZone.getTimeZone("America/Winnipeg"); //中央标准时间
    public static final TimeZone America_Yakutat = TimeZone.getTimeZone("America/Yakutat"); //阿拉斯加标准时间
    public static final TimeZone America_Yellowknife = TimeZone.getTimeZone("America/Yellowknife"); //Mountain 标准时间
    public static final TimeZone Antarctica_Casey = TimeZone.getTimeZone("Antarctica/Casey"); //西部标准时间（澳大利亚）
    public static final TimeZone Antarctica_Davis = TimeZone.getTimeZone("Antarctica/Davis"); //戴维斯时间
    public static final TimeZone Antarctica_DumontDUrville = TimeZone.getTimeZone("Antarctica/DumontDUrville"); //Dumont-d'Urville 时间
    public static final TimeZone Antarctica_Macquarie = TimeZone.getTimeZone("Antarctica/Macquarie"); //Macquarie Island Time
    public static final TimeZone Antarctica_Mawson = TimeZone.getTimeZone("Antarctica/Mawson"); //莫森时间
    public static final TimeZone Antarctica_McMurdo = TimeZone.getTimeZone("Antarctica/McMurdo"); //新西兰标准时间
    public static final TimeZone Antarctica_Palmer = TimeZone.getTimeZone("Antarctica/Palmer"); //智利时间
    public static final TimeZone Antarctica_Rothera = TimeZone.getTimeZone("Antarctica/Rothera"); //罗瑟拉时间
    public static final TimeZone Antarctica_South_Pole = TimeZone.getTimeZone("Antarctica/South_Pole"); //新西兰标准时间
    public static final TimeZone Antarctica_Syowa = TimeZone.getTimeZone("Antarctica/Syowa"); //Syowa 时间
    public static final TimeZone Antarctica_Vostok = TimeZone.getTimeZone("Antarctica/Vostok"); //莫斯托克时间
    public static final TimeZone Arctic_Longyearbyen = TimeZone.getTimeZone("Arctic/Longyearbyen"); //中欧时间
    public static final TimeZone ART = TimeZone.getTimeZone("ART"); //东欧时间
    public static final TimeZone Asia_Aden = TimeZone.getTimeZone("Asia/Aden"); //阿拉伯标准时间
    public static final TimeZone Asia_Almaty = TimeZone.getTimeZone("Asia/Almaty"); //Alma-Ata 时间
    public static final TimeZone Asia_Amman = TimeZone.getTimeZone("Asia/Amman"); //东欧时间
    public static final TimeZone Asia_Anadyr = TimeZone.getTimeZone("Asia/Anadyr"); //阿那底河时间
    public static final TimeZone Asia_Aqtau = TimeZone.getTimeZone("Asia/Aqtau"); //Aqtau 时间
    public static final TimeZone Asia_Aqtobe = TimeZone.getTimeZone("Asia/Aqtobe"); //Aqtobe 时间
    public static final TimeZone Asia_Ashgabat = TimeZone.getTimeZone("Asia/Ashgabat"); //土库曼时间
    public static final TimeZone Asia_Ashkhabad = TimeZone.getTimeZone("Asia/Ashkhabad"); //土库曼时间
    public static final TimeZone Asia_Baghdad = TimeZone.getTimeZone("Asia/Baghdad"); //阿拉伯标准时间
    public static final TimeZone Asia_Bahrain = TimeZone.getTimeZone("Asia/Bahrain"); //阿拉伯标准时间
    public static final TimeZone Asia_Baku = TimeZone.getTimeZone("Asia/Baku"); //亚塞拜然时间
    public static final TimeZone Asia_Bangkok = TimeZone.getTimeZone("Asia/Bangkok"); //印度支那时间
    public static final TimeZone Asia_Beirut = TimeZone.getTimeZone("Asia/Beirut"); //东欧时间
    public static final TimeZone Asia_Bishkek = TimeZone.getTimeZone("Asia/Bishkek"); //吉尔吉斯斯坦时间
    public static final TimeZone Asia_Brunei = TimeZone.getTimeZone("Asia/Brunei"); //文莱时间
    public static final TimeZone Asia_Calcutta = TimeZone.getTimeZone("Asia/Calcutta"); //印度标准时间
    public static final TimeZone Asia_Choibalsan = TimeZone.getTimeZone("Asia/Choibalsan"); //Choibalsan 时间
    public static final TimeZone Asia_Chongqing = TimeZone.getTimeZone("Asia/Chongqing"); //中国标准时间
    public static final TimeZone Asia_Chungking = TimeZone.getTimeZone("Asia/Chungking"); //中国标准时间
    public static final TimeZone Asia_Colombo = TimeZone.getTimeZone("Asia/Colombo"); //印度标准时间
    public static final TimeZone Asia_Dacca = TimeZone.getTimeZone("Asia/Dacca"); //孟加拉时间
    public static final TimeZone Asia_Damascus = TimeZone.getTimeZone("Asia/Damascus"); //东欧时间
    public static final TimeZone Asia_Dhaka = TimeZone.getTimeZone("Asia/Dhaka"); //孟加拉时间
    public static final TimeZone Asia_Dili = TimeZone.getTimeZone("Asia/Dili"); //东帝汶时间
    public static final TimeZone Asia_Dubai = TimeZone.getTimeZone("Asia/Dubai"); //波斯湾标准时间
    public static final TimeZone Asia_Dushanbe = TimeZone.getTimeZone("Asia/Dushanbe"); //塔吉克斯坦时间
    public static final TimeZone Asia_Gaza = TimeZone.getTimeZone("Asia/Gaza"); //东欧时间
    public static final TimeZone Asia_Harbin = TimeZone.getTimeZone("Asia/Harbin"); //中国标准时间
    public static final TimeZone Asia_Hebron = TimeZone.getTimeZone("Asia/Hebron"); //东欧时间
    public static final TimeZone Asia_Ho_Chi_Minh = TimeZone.getTimeZone("Asia/Ho_Chi_Minh"); //印度支那时间
    public static final TimeZone Asia_Hong_Kong = TimeZone.getTimeZone("Asia/Hong_Kong"); //香港时间
    public static final TimeZone Asia_Hovd = TimeZone.getTimeZone("Asia/Hovd"); //科布多时间
    public static final TimeZone Asia_Irkutsk = TimeZone.getTimeZone("Asia/Irkutsk"); //伊尔库次克时间
    public static final TimeZone Asia_Istanbul = TimeZone.getTimeZone("Asia/Istanbul"); //东欧时间
    public static final TimeZone Asia_Jakarta = TimeZone.getTimeZone("Asia/Jakarta"); //西印度尼西亚时间
    public static final TimeZone Asia_Jayapura = TimeZone.getTimeZone("Asia/Jayapura"); //东印度尼西亚时间
    public static final TimeZone Asia_Jerusalem = TimeZone.getTimeZone("Asia/Jerusalem"); //以色列标准时间
    public static final TimeZone Asia_Kabul = TimeZone.getTimeZone("Asia/Kabul"); //阿富汗时间
    public static final TimeZone Asia_Kamchatka = TimeZone.getTimeZone("Asia/Kamchatka"); //彼得罗巴甫洛夫斯克时间
    public static final TimeZone Asia_Karachi = TimeZone.getTimeZone("Asia/Karachi"); //巴基斯坦时间
    public static final TimeZone Asia_Kashgar = TimeZone.getTimeZone("Asia/Kashgar"); //中国标准时间
    public static final TimeZone Asia_Kathmandu = TimeZone.getTimeZone("Asia/Kathmandu"); //尼泊尔时间
    public static final TimeZone Asia_Katmandu = TimeZone.getTimeZone("Asia/Katmandu"); //尼泊尔时间
    public static final TimeZone Asia_Kolkata = TimeZone.getTimeZone("Asia/Kolkata"); //印度标准时间
    public static final TimeZone Asia_Krasnoyarsk = TimeZone.getTimeZone("Asia/Krasnoyarsk"); //克拉斯诺亚尔斯克时间
    public static final TimeZone Asia_Kuala_Lumpur = TimeZone.getTimeZone("Asia/Kuala_Lumpur"); //马来西亚时间
    public static final TimeZone Asia_Kuching = TimeZone.getTimeZone("Asia/Kuching"); //马来西亚时间
    public static final TimeZone Asia_Kuwait = TimeZone.getTimeZone("Asia/Kuwait"); //阿拉伯标准时间
    public static final TimeZone Asia_Macao = TimeZone.getTimeZone("Asia/Macao"); //中国标准时间
    public static final TimeZone Asia_Macau = TimeZone.getTimeZone("Asia/Macau"); //中国标准时间
    public static final TimeZone Asia_Magadan = TimeZone.getTimeZone("Asia/Magadan"); //Magadan 时间
    public static final TimeZone Asia_Makassar = TimeZone.getTimeZone("Asia/Makassar"); //中部印度尼西亚时间
    public static final TimeZone Asia_Manila = TimeZone.getTimeZone("Asia/Manila"); //菲律宾时间
    public static final TimeZone Asia_Muscat = TimeZone.getTimeZone("Asia/Muscat"); //波斯湾标准时间
    public static final TimeZone Asia_Nicosia = TimeZone.getTimeZone("Asia/Nicosia"); //东欧时间
    public static final TimeZone Asia_Novokuznetsk = TimeZone.getTimeZone("Asia/Novokuznetsk"); //Novosibirsk 时间
    public static final TimeZone Asia_Novosibirsk = TimeZone.getTimeZone("Asia/Novosibirsk"); //Novosibirsk 时间
    public static final TimeZone Asia_Omsk = TimeZone.getTimeZone("Asia/Omsk"); //鄂木斯克时间
    public static final TimeZone Asia_Oral = TimeZone.getTimeZone("Asia/Oral"); //Oral 时间
    public static final TimeZone Asia_Phnom_Penh = TimeZone.getTimeZone("Asia/Phnom_Penh"); //印度支那时间
    public static final TimeZone Asia_Pontianak = TimeZone.getTimeZone("Asia/Pontianak"); //西印度尼西亚时间
    public static final TimeZone Asia_Pyongyang = TimeZone.getTimeZone("Asia/Pyongyang"); //韩国标准时间
    public static final TimeZone Asia_Qatar = TimeZone.getTimeZone("Asia/Qatar"); //阿拉伯标准时间
    public static final TimeZone Asia_Qyzylorda = TimeZone.getTimeZone("Asia/Qyzylorda"); //Qyzylorda 时间
    public static final TimeZone Asia_Rangoon = TimeZone.getTimeZone("Asia/Rangoon"); //缅甸时间
    public static final TimeZone Asia_Riyadh = TimeZone.getTimeZone("Asia/Riyadh"); //阿拉伯标准时间
    public static final TimeZone Asia_Riyadh87 = TimeZone.getTimeZone("Asia/Riyadh87"); //GMT+03:07
    public static final TimeZone Asia_Riyadh88 = TimeZone.getTimeZone("Asia/Riyadh88"); //GMT+03:07
    public static final TimeZone Asia_Riyadh89 = TimeZone.getTimeZone("Asia/Riyadh89"); //GMT+03:07
    public static final TimeZone Asia_Saigon = TimeZone.getTimeZone("Asia/Saigon"); //印度支那时间
    public static final TimeZone Asia_Sakhalin = TimeZone.getTimeZone("Asia/Sakhalin"); //库页岛时间
    public static final TimeZone Asia_Samarkand = TimeZone.getTimeZone("Asia/Samarkand"); //乌兹别克斯坦时间
    public static final TimeZone Asia_Seoul = TimeZone.getTimeZone("Asia/Seoul"); //韩国标准时间
    public static final TimeZone Asia_Shanghai = TimeZone.getTimeZone("Asia/Shanghai"); //中国标准时间
    public static final TimeZone Asia_Singapore = TimeZone.getTimeZone("Asia/Singapore"); //新加坡时间
    public static final TimeZone Asia_Taipei = TimeZone.getTimeZone("Asia/Taipei"); //中国标准时间
    public static final TimeZone Asia_Tashkent = TimeZone.getTimeZone("Asia/Tashkent"); //乌兹别克斯坦时间
    public static final TimeZone Asia_Tbilisi = TimeZone.getTimeZone("Asia/Tbilisi"); //乔治亚时间
    public static final TimeZone Asia_Tehran = TimeZone.getTimeZone("Asia/Tehran"); //伊朗标准时间
    public static final TimeZone Asia_Tel_Aviv = TimeZone.getTimeZone("Asia/Tel_Aviv"); //以色列标准时间
    public static final TimeZone Asia_Thimbu = TimeZone.getTimeZone("Asia/Thimbu"); //不丹时间
    public static final TimeZone Asia_Thimphu = TimeZone.getTimeZone("Asia/Thimphu"); //不丹时间
    public static final TimeZone Asia_Tokyo = TimeZone.getTimeZone("Asia/Tokyo"); //日本标准时间
    public static final TimeZone Asia_Ujung_Pandang = TimeZone.getTimeZone("Asia/Ujung_Pandang"); //中部印度尼西亚时间
    public static final TimeZone Asia_Ulaanbaatar = TimeZone.getTimeZone("Asia/Ulaanbaatar"); //库伦时间
    public static final TimeZone Asia_Ulan_Bator = TimeZone.getTimeZone("Asia/Ulan_Bator"); //库伦时间
    public static final TimeZone Asia_Urumqi = TimeZone.getTimeZone("Asia/Urumqi"); //中国标准时间
    public static final TimeZone Asia_Vientiane = TimeZone.getTimeZone("Asia/Vientiane"); //印度支那时间
    public static final TimeZone Asia_Vladivostok = TimeZone.getTimeZone("Asia/Vladivostok"); //海参崴时间
    public static final TimeZone Asia_Yakutsk = TimeZone.getTimeZone("Asia/Yakutsk"); //亚库次克时间
    public static final TimeZone Asia_Yekaterinburg = TimeZone.getTimeZone("Asia/Yekaterinburg"); //Yekaterinburg 时间
    public static final TimeZone Asia_Yerevan = TimeZone.getTimeZone("Asia/Yerevan"); //亚美尼亚时间
    public static final TimeZone AST = TimeZone.getTimeZone("AST"); //阿拉斯加标准时间
    public static final TimeZone Atlantic_Azores = TimeZone.getTimeZone("Atlantic/Azores"); //亚速尔群岛时间
    public static final TimeZone Atlantic_Bermuda = TimeZone.getTimeZone("Atlantic/Bermuda"); //大西洋标准时间
    public static final TimeZone Atlantic_Canary = TimeZone.getTimeZone("Atlantic/Canary"); //西欧时间
    public static final TimeZone Atlantic_Cape_Verde = TimeZone.getTimeZone("Atlantic/Cape_Verde"); //佛德角时间
    public static final TimeZone Atlantic_Faeroe = TimeZone.getTimeZone("Atlantic/Faeroe"); //西欧时间
    public static final TimeZone Atlantic_Faroe = TimeZone.getTimeZone("Atlantic/Faroe"); //西欧时间
    public static final TimeZone Atlantic_Jan_Mayen = TimeZone.getTimeZone("Atlantic/Jan_Mayen"); //中欧时间
    public static final TimeZone Atlantic_Madeira = TimeZone.getTimeZone("Atlantic/Madeira"); //西欧时间
    public static final TimeZone Atlantic_Reykjavik = TimeZone.getTimeZone("Atlantic/Reykjavik"); //格林威治时间
    public static final TimeZone Atlantic_South_Georgia = TimeZone.getTimeZone("Atlantic/South_Georgia"); //南乔治亚标准时间
    public static final TimeZone Atlantic_St_Helena = TimeZone.getTimeZone("Atlantic/St_Helena"); //格林威治时间
    public static final TimeZone Atlantic_Stanley = TimeZone.getTimeZone("Atlantic/Stanley"); //福克兰群岛时间
    public static final TimeZone Australia_ACT = TimeZone.getTimeZone("Australia/ACT"); //东部标准时间（新南威尔斯）
    public static final TimeZone Australia_Adelaide = TimeZone.getTimeZone("Australia/Adelaide"); //中央标准时间（南澳大利亚）
    public static final TimeZone Australia_Brisbane = TimeZone.getTimeZone("Australia/Brisbane"); //东部标准时间（昆士兰）
    public static final TimeZone Australia_Broken_Hill = TimeZone.getTimeZone("Australia/Broken_Hill"); //中央标准时间（南澳大利亚/新南威尔斯）
    public static final TimeZone Australia_Canberra = TimeZone.getTimeZone("Australia/Canberra"); //东部标准时间（新南威尔斯）
    public static final TimeZone Australia_Currie = TimeZone.getTimeZone("Australia/Currie"); //东部标准时间（新南威尔斯）
    public static final TimeZone Australia_Darwin = TimeZone.getTimeZone("Australia/Darwin"); //中央标准时间（北领地）
    public static final TimeZone Australia_Eucla = TimeZone.getTimeZone("Australia/Eucla"); //中西部标准时间（澳大利亚）
    public static final TimeZone Australia_Hobart = TimeZone.getTimeZone("Australia/Hobart"); //东部标准时间（塔斯马尼亚）
    public static final TimeZone Australia_LHI = TimeZone.getTimeZone("Australia/LHI"); //豪公标准时间
    public static final TimeZone Australia_Lindeman = TimeZone.getTimeZone("Australia/Lindeman"); //东部标准时间（昆士兰）
    public static final TimeZone Australia_Lord_Howe = TimeZone.getTimeZone("Australia/Lord_Howe"); //豪公标准时间
    public static final TimeZone Australia_Melbourne = TimeZone.getTimeZone("Australia/Melbourne"); //东部标准时间（维多利亚）
    public static final TimeZone Australia_North = TimeZone.getTimeZone("Australia/North"); //中央标准时间（北领地）
    public static final TimeZone Australia_NSW = TimeZone.getTimeZone("Australia/NSW"); //东部标准时间（新南威尔斯）
    public static final TimeZone Australia_Perth = TimeZone.getTimeZone("Australia/Perth"); //西部标准时间（澳大利亚）
    public static final TimeZone Australia_Queensland = TimeZone.getTimeZone("Australia/Queensland"); //东部标准时间（昆士兰）
    public static final TimeZone Australia_South = TimeZone.getTimeZone("Australia/South"); //中央标准时间（南澳大利亚）
    public static final TimeZone Australia_Sydney = TimeZone.getTimeZone("Australia/Sydney"); //东部标准时间（新南威尔斯）
    public static final TimeZone Australia_Tasmania = TimeZone.getTimeZone("Australia/Tasmania"); //东部标准时间（塔斯马尼亚）
    public static final TimeZone Australia_Victoria = TimeZone.getTimeZone("Australia/Victoria"); //东部标准时间（维多利亚）
    public static final TimeZone Australia_West = TimeZone.getTimeZone("Australia/West"); //西部标准时间（澳大利亚）
    public static final TimeZone Australia_Yancowinna = TimeZone.getTimeZone("Australia/Yancowinna"); //中央标准时间（南澳大利亚/新南威尔斯）
    public static final TimeZone BET = TimeZone.getTimeZone("BET"); //巴西利亚时间
    public static final TimeZone Brazil_Acre = TimeZone.getTimeZone("Brazil/Acre"); //亚马逊时间
    public static final TimeZone Brazil_DeNoronha = TimeZone.getTimeZone("Brazil/DeNoronha"); //费尔南多德诺罗尼亚时间
    public static final TimeZone Brazil_East = TimeZone.getTimeZone("Brazil/East"); //巴西利亚时间
    public static final TimeZone Brazil_West = TimeZone.getTimeZone("Brazil/West"); //亚马逊时间
    public static final TimeZone BST = TimeZone.getTimeZone("BST"); //孟加拉时间
    public static final TimeZone Canada_Atlantic = TimeZone.getTimeZone("Canada/Atlantic"); //大西洋标准时间
    public static final TimeZone Canada_Central = TimeZone.getTimeZone("Canada/Central"); //中央标准时间
    public static final TimeZone Canada_East_Saskatchewan = TimeZone.getTimeZone("Canada/East-Saskatchewan"); //中央标准时间
    public static final TimeZone Canada_Eastern = TimeZone.getTimeZone("Canada/Eastern"); //东部标准时间
    public static final TimeZone Canada_Mountain = TimeZone.getTimeZone("Canada/Mountain"); //Mountain 标准时间
    public static final TimeZone Canada_Newfoundland = TimeZone.getTimeZone("Canada/Newfoundland"); //纽芬兰标准时间
    public static final TimeZone Canada_Pacific = TimeZone.getTimeZone("Canada/Pacific"); //太平洋标准时间
    public static final TimeZone Canada_Saskatchewan = TimeZone.getTimeZone("Canada/Saskatchewan"); //中央标准时间
    public static final TimeZone Canada_Yukon = TimeZone.getTimeZone("Canada/Yukon"); //太平洋标准时间
    public static final TimeZone CAT = TimeZone.getTimeZone("CAT"); //中非时间
    public static final TimeZone CET = TimeZone.getTimeZone("CET"); //中欧时间
    public static final TimeZone Chile_Continental = TimeZone.getTimeZone("Chile/Continental"); //智利时间
    public static final TimeZone Chile_EasterIsland = TimeZone.getTimeZone("Chile/EasterIsland"); //复活岛时间
    public static final TimeZone CNT = TimeZone.getTimeZone("CNT"); //纽芬兰标准时间
    public static final TimeZone CST = TimeZone.getTimeZone("CST"); //中央标准时间
    public static final TimeZone CST6CDT = TimeZone.getTimeZone("CST6CDT"); //中央标准时间
    public static final TimeZone CTT = TimeZone.getTimeZone("CTT"); //中国标准时间
    public static final TimeZone Cuba = TimeZone.getTimeZone("Cuba"); //古巴标准时间
    public static final TimeZone EAT = TimeZone.getTimeZone("EAT"); //东非时间
    public static final TimeZone ECT = TimeZone.getTimeZone("ECT"); //中欧时间
    public static final TimeZone EET = TimeZone.getTimeZone("EET"); //东欧时间
    public static final TimeZone Egypt = TimeZone.getTimeZone("Egypt"); //东欧时间
    public static final TimeZone Eire = TimeZone.getTimeZone("Eire"); //格林威治时间
    public static final TimeZone EST = TimeZone.getTimeZone("EST"); //东部标准时间
    public static final TimeZone EST5EDT = TimeZone.getTimeZone("EST5EDT"); //东部标准时间
    public static final TimeZone Etc_GMT = TimeZone.getTimeZone("Etc/GMT"); //GMT+00:00
    public static final TimeZone Etc_GMT1 = TimeZone.getTimeZone("Etc/GMT+1"); //GMT-01:00
    public static final TimeZone Etc_GMT10 = TimeZone.getTimeZone("Etc/GMT+10"); //GMT-10:00
    public static final TimeZone Etc_GMT11 = TimeZone.getTimeZone("Etc/GMT+11"); //GMT-11:00
    public static final TimeZone Etc_GMT12 = TimeZone.getTimeZone("Etc/GMT+12"); //GMT-12:00
    public static final TimeZone Etc_GMT2 = TimeZone.getTimeZone("Etc/GMT+2"); //GMT-02:00
    public static final TimeZone Etc_GMT3 = TimeZone.getTimeZone("Etc/GMT+3"); //GMT-03:00
    public static final TimeZone Etc_GMT4 = TimeZone.getTimeZone("Etc/GMT+4"); //GMT-04:00
    public static final TimeZone Etc_GMT5 = TimeZone.getTimeZone("Etc/GMT+5"); //GMT-05:00
    public static final TimeZone Etc_GMT6 = TimeZone.getTimeZone("Etc/GMT+6"); //GMT-06:00
    public static final TimeZone Etc_GMT7 = TimeZone.getTimeZone("Etc/GMT+7"); //GMT-07:00
    public static final TimeZone Etc_GMT8 = TimeZone.getTimeZone("Etc/GMT+8"); //GMT-08:00
    public static final TimeZone Etc_GMT9 = TimeZone.getTimeZone("Etc/GMT+9"); //GMT-09:00
    public static final TimeZone Etc_GMT_0 = TimeZone.getTimeZone("Etc/GMT-0"); //GMT+00:00
    public static final TimeZone Etc_GMT_1 = TimeZone.getTimeZone("Etc/GMT-1"); //GMT+01:00
    public static final TimeZone Etc_GMT_10 = TimeZone.getTimeZone("Etc/GMT-10"); //GMT+10:00
    public static final TimeZone Etc_GMT_11 = TimeZone.getTimeZone("Etc/GMT-11"); //GMT+11:00
    public static final TimeZone Etc_GMT_12 = TimeZone.getTimeZone("Etc/GMT-12"); //GMT+12:00
    public static final TimeZone Etc_GMT_13 = TimeZone.getTimeZone("Etc/GMT-13"); //GMT+13:00
    public static final TimeZone Etc_GMT_14 = TimeZone.getTimeZone("Etc/GMT-14"); //GMT+14:00
    public static final TimeZone Etc_GMT_2 = TimeZone.getTimeZone("Etc/GMT-2"); //GMT+02:00
    public static final TimeZone Etc_GMT_3 = TimeZone.getTimeZone("Etc/GMT-3"); //GMT+03:00
    public static final TimeZone Etc_GMT_4 = TimeZone.getTimeZone("Etc/GMT-4"); //GMT+04:00
    public static final TimeZone Etc_GMT_5 = TimeZone.getTimeZone("Etc/GMT-5"); //GMT+05:00
    public static final TimeZone Etc_GMT_6 = TimeZone.getTimeZone("Etc/GMT-6"); //GMT+06:00
    public static final TimeZone Etc_GMT_7 = TimeZone.getTimeZone("Etc/GMT-7"); //GMT+07:00
    public static final TimeZone Etc_GMT_8 = TimeZone.getTimeZone("Etc/GMT-8"); //GMT+08:00
    public static final TimeZone Etc_GMT_9 = TimeZone.getTimeZone("Etc/GMT-9"); //GMT+09:00
    public static final TimeZone Etc_GMT0 = TimeZone.getTimeZone("Etc/GMT0"); //GMT+00:00
    public static final TimeZone Etc_Greenwich = TimeZone.getTimeZone("Etc/Greenwich"); //格林威治时间
    public static final TimeZone Etc_UCT = TimeZone.getTimeZone("Etc/UCT"); //协调世界时间
    public static final TimeZone Etc_Universal = TimeZone.getTimeZone("Etc/Universal"); //协调世界时间
    public static final TimeZone Etc_UTC = TimeZone.getTimeZone("Etc/UTC"); //协调世界时间
    public static final TimeZone Etc_Zulu = TimeZone.getTimeZone("Etc/Zulu"); //协调世界时间
    public static final TimeZone Europe_Amsterdam = TimeZone.getTimeZone("Europe/Amsterdam"); //中欧时间
    public static final TimeZone Europe_Andorra = TimeZone.getTimeZone("Europe/Andorra"); //中欧时间
    public static final TimeZone Europe_Athens = TimeZone.getTimeZone("Europe/Athens"); //东欧时间
    public static final TimeZone Europe_Belfast = TimeZone.getTimeZone("Europe/Belfast"); //格林威治时间
    public static final TimeZone Europe_Belgrade = TimeZone.getTimeZone("Europe/Belgrade"); //中欧时间
    public static final TimeZone Europe_Berlin = TimeZone.getTimeZone("Europe/Berlin"); //中欧时间
    public static final TimeZone Europe_Bratislava = TimeZone.getTimeZone("Europe/Bratislava"); //中欧时间
    public static final TimeZone Europe_Brussels = TimeZone.getTimeZone("Europe/Brussels"); //中欧时间
    public static final TimeZone Europe_Bucharest = TimeZone.getTimeZone("Europe/Bucharest"); //东欧时间
    public static final TimeZone Europe_Budapest = TimeZone.getTimeZone("Europe/Budapest"); //中欧时间
    public static final TimeZone Europe_Chisinau = TimeZone.getTimeZone("Europe/Chisinau"); //东欧时间
    public static final TimeZone Europe_Copenhagen = TimeZone.getTimeZone("Europe/Copenhagen"); //中欧时间
    public static final TimeZone Europe_Dublin = TimeZone.getTimeZone("Europe/Dublin"); //格林威治时间
    public static final TimeZone Europe_Gibraltar = TimeZone.getTimeZone("Europe/Gibraltar"); //中欧时间
    public static final TimeZone Europe_Guernsey = TimeZone.getTimeZone("Europe/Guernsey"); //格林威治时间
    public static final TimeZone Europe_Helsinki = TimeZone.getTimeZone("Europe/Helsinki"); //东欧时间
    public static final TimeZone Europe_Isle_of_Man = TimeZone.getTimeZone("Europe/Isle_of_Man"); //格林威治时间
    public static final TimeZone Europe_Istanbul = TimeZone.getTimeZone("Europe/Istanbul"); //东欧时间
    public static final TimeZone Europe_Jersey = TimeZone.getTimeZone("Europe/Jersey"); //格林威治时间
    public static final TimeZone Europe_Kaliningrad = TimeZone.getTimeZone("Europe/Kaliningrad"); //Further-eastern European Time
    public static final TimeZone Europe_Kiev = TimeZone.getTimeZone("Europe/Kiev"); //东欧时间
    public static final TimeZone Europe_Lisbon = TimeZone.getTimeZone("Europe/Lisbon"); //西欧时间
    public static final TimeZone Europe_Ljubljana = TimeZone.getTimeZone("Europe/Ljubljana"); //中欧时间
    public static final TimeZone Europe_London = TimeZone.getTimeZone("Europe/London"); //格林威治时间
    public static final TimeZone Europe_Luxembourg = TimeZone.getTimeZone("Europe/Luxembourg"); //中欧时间
    public static final TimeZone Europe_Madrid = TimeZone.getTimeZone("Europe/Madrid"); //中欧时间
    public static final TimeZone Europe_Malta = TimeZone.getTimeZone("Europe/Malta"); //中欧时间
    public static final TimeZone Europe_Mariehamn = TimeZone.getTimeZone("Europe/Mariehamn"); //东欧时间
    public static final TimeZone Europe_Minsk = TimeZone.getTimeZone("Europe/Minsk"); //Further-eastern European Time
    public static final TimeZone Europe_Monaco = TimeZone.getTimeZone("Europe/Monaco"); //中欧时间
    public static final TimeZone Europe_Moscow = TimeZone.getTimeZone("Europe/Moscow"); //莫斯科标准时间
    public static final TimeZone Europe_Nicosia = TimeZone.getTimeZone("Europe/Nicosia"); //东欧时间
    public static final TimeZone Europe_Oslo = TimeZone.getTimeZone("Europe/Oslo"); //中欧时间
    public static final TimeZone Europe_Paris = TimeZone.getTimeZone("Europe/Paris"); //中欧时间
    public static final TimeZone Europe_Podgorica = TimeZone.getTimeZone("Europe/Podgorica"); //中欧时间
    public static final TimeZone Europe_Prague = TimeZone.getTimeZone("Europe/Prague"); //中欧时间
    public static final TimeZone Europe_Riga = TimeZone.getTimeZone("Europe/Riga"); //东欧时间
    public static final TimeZone Europe_Rome = TimeZone.getTimeZone("Europe/Rome"); //中欧时间
    public static final TimeZone Europe_Samara = TimeZone.getTimeZone("Europe/Samara"); //沙马拉时间
    public static final TimeZone Europe_San_Marino = TimeZone.getTimeZone("Europe/San_Marino"); //中欧时间
    public static final TimeZone Europe_Sarajevo = TimeZone.getTimeZone("Europe/Sarajevo"); //中欧时间
    public static final TimeZone Europe_Simferopol = TimeZone.getTimeZone("Europe/Simferopol"); //东欧时间
    public static final TimeZone Europe_Skopje = TimeZone.getTimeZone("Europe/Skopje"); //中欧时间
    public static final TimeZone Europe_Sofia = TimeZone.getTimeZone("Europe/Sofia"); //东欧时间
    public static final TimeZone Europe_Stockholm = TimeZone.getTimeZone("Europe/Stockholm"); //中欧时间
    public static final TimeZone Europe_Tallinn = TimeZone.getTimeZone("Europe/Tallinn"); //东欧时间
    public static final TimeZone Europe_Tirane = TimeZone.getTimeZone("Europe/Tirane"); //中欧时间
    public static final TimeZone Europe_Tiraspol = TimeZone.getTimeZone("Europe/Tiraspol"); //东欧时间
    public static final TimeZone Europe_Uzhgorod = TimeZone.getTimeZone("Europe/Uzhgorod"); //东欧时间
    public static final TimeZone Europe_Vaduz = TimeZone.getTimeZone("Europe/Vaduz"); //中欧时间
    public static final TimeZone Europe_Vatican = TimeZone.getTimeZone("Europe/Vatican"); //中欧时间
    public static final TimeZone Europe_Vienna = TimeZone.getTimeZone("Europe/Vienna"); //中欧时间
    public static final TimeZone Europe_Vilnius = TimeZone.getTimeZone("Europe/Vilnius"); //东欧时间
    public static final TimeZone Europe_Volgograd = TimeZone.getTimeZone("Europe/Volgograd"); //伏尔加格勒时间
    public static final TimeZone Europe_Warsaw = TimeZone.getTimeZone("Europe/Warsaw"); //中欧时间
    public static final TimeZone Europe_Zagreb = TimeZone.getTimeZone("Europe/Zagreb"); //中欧时间
    public static final TimeZone Europe_Zaporozhye = TimeZone.getTimeZone("Europe/Zaporozhye"); //东欧时间
    public static final TimeZone Europe_Zurich = TimeZone.getTimeZone("Europe/Zurich"); //中欧时间
    public static final TimeZone GB = TimeZone.getTimeZone("GB"); //格林威治时间
    public static final TimeZone GB_Eire = TimeZone.getTimeZone("GB-Eire"); //格林威治时间
    public static final TimeZone GMT = TimeZone.getTimeZone("GMT"); //格林威治时间
    public static final TimeZone GMT0 = TimeZone.getTimeZone("GMT0"); //GMT+00:00
    public static final TimeZone Greenwich = TimeZone.getTimeZone("Greenwich"); //格林威治时间
    public static final TimeZone Hongkong = TimeZone.getTimeZone("Hongkong"); //香港时间
    public static final TimeZone HST = TimeZone.getTimeZone("HST"); //夏威夷标准时间
    public static final TimeZone Iceland = TimeZone.getTimeZone("Iceland"); //格林威治时间
    public static final TimeZone IET = TimeZone.getTimeZone("IET"); //东部标准时间
    public static final TimeZone Indian_Antananarivo = TimeZone.getTimeZone("Indian/Antananarivo"); //东非时间
    public static final TimeZone Indian_Chagos = TimeZone.getTimeZone("Indian/Chagos"); //印度洋地带时间
    public static final TimeZone Indian_Christmas = TimeZone.getTimeZone("Indian/Christmas"); //圣诞岛时间
    public static final TimeZone Indian_Cocos = TimeZone.getTimeZone("Indian/Cocos"); //可可斯群岛时间
    public static final TimeZone Indian_Comoro = TimeZone.getTimeZone("Indian/Comoro"); //东非时间
    public static final TimeZone Indian_Kerguelen = TimeZone.getTimeZone("Indian/Kerguelen"); //法属南极时间
    public static final TimeZone Indian_Mahe = TimeZone.getTimeZone("Indian/Mahe"); //塞席尔群岛时间
    public static final TimeZone Indian_Maldives = TimeZone.getTimeZone("Indian/Maldives"); //马尔代夫时间
    public static final TimeZone Indian_Mauritius = TimeZone.getTimeZone("Indian/Mauritius"); //摩里西斯时间
    public static final TimeZone Indian_Mayotte = TimeZone.getTimeZone("Indian/Mayotte"); //东非时间
    public static final TimeZone Indian_Reunion = TimeZone.getTimeZone("Indian/Reunion"); //留尼旺岛时间
    public static final TimeZone Iran = TimeZone.getTimeZone("Iran"); //伊朗标准时间
    public static final TimeZone Israel = TimeZone.getTimeZone("Israel"); //以色列标准时间
    public static final TimeZone IST = TimeZone.getTimeZone("IST"); //印度标准时间
    public static final TimeZone Jamaica = TimeZone.getTimeZone("Jamaica"); //东部标准时间
    public static final TimeZone Japan = TimeZone.getTimeZone("Japan"); //日本标准时间
    public static final TimeZone JST = TimeZone.getTimeZone("JST"); //日本标准时间
    public static final TimeZone Kwajalein = TimeZone.getTimeZone("Kwajalein"); //马绍尔群岛时间
    public static final TimeZone Libya = TimeZone.getTimeZone("Libya"); //东欧时间
    public static final TimeZone MET = TimeZone.getTimeZone("MET"); //中欧时间
    public static final TimeZone Mexico_BajaNorte = TimeZone.getTimeZone("Mexico/BajaNorte"); //太平洋标准时间
    public static final TimeZone Mexico_BajaSur = TimeZone.getTimeZone("Mexico/BajaSur"); //Mountain 标准时间
    public static final TimeZone Mexico_General = TimeZone.getTimeZone("Mexico/General"); //中央标准时间
    public static final TimeZone Mideast_Riyadh87 = TimeZone.getTimeZone("Mideast/Riyadh87"); //GMT+03:07
    public static final TimeZone Mideast_Riyadh88 = TimeZone.getTimeZone("Mideast/Riyadh88"); //GMT+03:07
    public static final TimeZone Mideast_Riyadh89 = TimeZone.getTimeZone("Mideast/Riyadh89"); //GMT+03:07
    public static final TimeZone MIT = TimeZone.getTimeZone("MIT"); //西萨摩亚时间
    public static final TimeZone MST = TimeZone.getTimeZone("MST"); //Mountain 标准时间
    public static final TimeZone MST7MDT = TimeZone.getTimeZone("MST7MDT"); //Mountain 标准时间
    public static final TimeZone Navajo = TimeZone.getTimeZone("Navajo"); //Mountain 标准时间
    public static final TimeZone NET = TimeZone.getTimeZone("NET"); //亚美尼亚时间
    public static final TimeZone NST = TimeZone.getTimeZone("NST"); //新西兰标准时间
    public static final TimeZone NZ = TimeZone.getTimeZone("NZ"); //新西兰标准时间
    public static final TimeZone NZ_CHAT = TimeZone.getTimeZone("NZ-CHAT"); //查萨姆标准时间
    public static final TimeZone Pacific_Apia = TimeZone.getTimeZone("Pacific/Apia"); //西萨摩亚时间
    public static final TimeZone Pacific_Auckland = TimeZone.getTimeZone("Pacific/Auckland"); //新西兰标准时间
    public static final TimeZone Pacific_Chatham = TimeZone.getTimeZone("Pacific/Chatham"); //查萨姆标准时间
    public static final TimeZone Pacific_Chuuk = TimeZone.getTimeZone("Pacific/Chuuk"); //Chuuk Time
    public static final TimeZone Pacific_Easter = TimeZone.getTimeZone("Pacific/Easter"); //复活岛时间
    public static final TimeZone Pacific_Efate = TimeZone.getTimeZone("Pacific/Efate"); //瓦奴阿图时间
    public static final TimeZone Pacific_Enderbury = TimeZone.getTimeZone("Pacific/Enderbury"); //菲尼克斯群岛时间
    public static final TimeZone Pacific_Fakaofo = TimeZone.getTimeZone("Pacific/Fakaofo"); //托克劳群岛时间
    public static final TimeZone Pacific_Fiji = TimeZone.getTimeZone("Pacific/Fiji"); //斐济时间
    public static final TimeZone Pacific_Funafuti = TimeZone.getTimeZone("Pacific/Funafuti"); //吐鲁瓦时间
    public static final TimeZone Pacific_Galapagos = TimeZone.getTimeZone("Pacific/Galapagos"); //加拉巴哥时间
    public static final TimeZone Pacific_Gambier = TimeZone.getTimeZone("Pacific/Gambier"); //冈比亚时间
    public static final TimeZone Pacific_Guadalcanal = TimeZone.getTimeZone("Pacific/Guadalcanal"); //所罗门群岛时间
    public static final TimeZone Pacific_Guam = TimeZone.getTimeZone("Pacific/Guam"); //Chamorro 标准时间
    public static final TimeZone Pacific_Honolulu = TimeZone.getTimeZone("Pacific/Honolulu"); //夏威夷标准时间
    public static final TimeZone Pacific_Johnston = TimeZone.getTimeZone("Pacific/Johnston"); //夏威夷标准时间
    public static final TimeZone Pacific_Kiritimati = TimeZone.getTimeZone("Pacific/Kiritimati"); //Line 岛时间
    public static final TimeZone Pacific_Kosrae = TimeZone.getTimeZone("Pacific/Kosrae"); //Kosrae 时间
    public static final TimeZone Pacific_Kwajalein = TimeZone.getTimeZone("Pacific/Kwajalein"); //马绍尔群岛时间
    public static final TimeZone Pacific_Majuro = TimeZone.getTimeZone("Pacific/Majuro"); //马绍尔群岛时间
    public static final TimeZone Pacific_Marquesas = TimeZone.getTimeZone("Pacific/Marquesas"); //马克萨斯时间
    public static final TimeZone Pacific_Midway = TimeZone.getTimeZone("Pacific/Midway"); //萨摩亚群岛标准时间
    public static final TimeZone Pacific_Nauru = TimeZone.getTimeZone("Pacific/Nauru"); //诺鲁时间
    public static final TimeZone Pacific_Niue = TimeZone.getTimeZone("Pacific/Niue"); //纽威岛时间
    public static final TimeZone Pacific_Norfolk = TimeZone.getTimeZone("Pacific/Norfolk"); //诺福克时间
    public static final TimeZone Pacific_Noumea = TimeZone.getTimeZone("Pacific/Noumea"); //新加勒多尼亚时间
    public static final TimeZone Pacific_Pago_Pago = TimeZone.getTimeZone("Pacific/Pago_Pago"); //萨摩亚群岛标准时间
    public static final TimeZone Pacific_Palau = TimeZone.getTimeZone("Pacific/Palau"); //帛琉时间
    public static final TimeZone Pacific_Pitcairn = TimeZone.getTimeZone("Pacific/Pitcairn"); //皮特康岛标准时间
    public static final TimeZone Pacific_Pohnpei = TimeZone.getTimeZone("Pacific/Pohnpei"); //Pohnpei Time
    public static final TimeZone Pacific_Ponape = TimeZone.getTimeZone("Pacific/Ponape"); //Pohnpei Time
    public static final TimeZone Pacific_Port_Moresby = TimeZone.getTimeZone("Pacific/Port_Moresby"); //巴布亚新几内亚时间
    public static final TimeZone Pacific_Rarotonga = TimeZone.getTimeZone("Pacific/Rarotonga"); //库克群岛时间
    public static final TimeZone Pacific_Saipan = TimeZone.getTimeZone("Pacific/Saipan"); //Chamorro 标准时间
    public static final TimeZone Pacific_Samoa = TimeZone.getTimeZone("Pacific/Samoa"); //萨摩亚群岛标准时间
    public static final TimeZone Pacific_Tahiti = TimeZone.getTimeZone("Pacific/Tahiti"); //大溪地岛时间
    public static final TimeZone Pacific_Tarawa = TimeZone.getTimeZone("Pacific/Tarawa"); //吉伯特群岛时间
    public static final TimeZone Pacific_Tongatapu = TimeZone.getTimeZone("Pacific/Tongatapu"); //东加时间
    public static final TimeZone Pacific_Truk = TimeZone.getTimeZone("Pacific/Truk"); //Chuuk Time
    public static final TimeZone Pacific_Wake = TimeZone.getTimeZone("Pacific/Wake"); //威克时间
    public static final TimeZone Pacific_Wallis = TimeZone.getTimeZone("Pacific/Wallis"); //瓦利斯及福杜纳群岛时间
    public static final TimeZone Pacific_Yap = TimeZone.getTimeZone("Pacific/Yap"); //Chuuk Time
    public static final TimeZone PLT = TimeZone.getTimeZone("PLT"); //巴基斯坦时间
    public static final TimeZone PNT = TimeZone.getTimeZone("PNT"); //Mountain 标准时间
    public static final TimeZone Poland = TimeZone.getTimeZone("Poland"); //中欧时间
    public static final TimeZone Portugal = TimeZone.getTimeZone("Portugal"); //西欧时间
    public static final TimeZone PRC = TimeZone.getTimeZone("PRC"); //中国标准时间
    public static final TimeZone PRT = TimeZone.getTimeZone("PRT"); //大西洋标准时间
    public static final TimeZone PST = TimeZone.getTimeZone("PST"); //太平洋标准时间
    public static final TimeZone PST8PDT = TimeZone.getTimeZone("PST8PDT"); //太平洋标准时间
    public static final TimeZone ROK = TimeZone.getTimeZone("ROK"); //韩国标准时间
    public static final TimeZone Singapore = TimeZone.getTimeZone("Singapore"); //新加坡时间
    public static final TimeZone SST = TimeZone.getTimeZone("SST"); //所罗门群岛时间
    public static final TimeZone SystemV_AST4 = TimeZone.getTimeZone("SystemV/AST4"); //大西洋标准时间
    public static final TimeZone SystemV_AST4ADT = TimeZone.getTimeZone("SystemV/AST4ADT"); //大西洋标准时间
    public static final TimeZone SystemV_CST6 = TimeZone.getTimeZone("SystemV/CST6"); //中央标准时间
    public static final TimeZone SystemV_CST6CDT = TimeZone.getTimeZone("SystemV/CST6CDT"); //中央标准时间
    public static final TimeZone SystemV_EST5 = TimeZone.getTimeZone("SystemV/EST5"); //东部标准时间
    public static final TimeZone SystemV_EST5EDT = TimeZone.getTimeZone("SystemV/EST5EDT"); //东部标准时间
    public static final TimeZone SystemV_HST10 = TimeZone.getTimeZone("SystemV/HST10"); //夏威夷标准时间
    public static final TimeZone SystemV_MST7 = TimeZone.getTimeZone("SystemV/MST7"); //Mountain 标准时间
    public static final TimeZone SystemV_MST7MDT = TimeZone.getTimeZone("SystemV/MST7MDT"); //Mountain 标准时间
    public static final TimeZone SystemV_PST8 = TimeZone.getTimeZone("SystemV/PST8"); //太平洋标准时间
    public static final TimeZone SystemV_PST8PDT = TimeZone.getTimeZone("SystemV/PST8PDT"); //太平洋标准时间
    public static final TimeZone SystemV_YST9 = TimeZone.getTimeZone("SystemV/YST9"); //阿拉斯加标准时间
    public static final TimeZone SystemV_YST9YDT = TimeZone.getTimeZone("SystemV/YST9YDT"); //阿拉斯加标准时间
    public static final TimeZone Turkey = TimeZone.getTimeZone("Turkey"); //东欧时间
    public static final TimeZone UCT = TimeZone.getTimeZone("UCT"); //协调世界时间
    public static final TimeZone Universal = TimeZone.getTimeZone("Universal"); //协调世界时间
    public static final TimeZone US_Alaska = TimeZone.getTimeZone("US/Alaska"); //阿拉斯加标准时间
    public static final TimeZone US_Aleutian = TimeZone.getTimeZone("US/Aleutian"); //夏威夷-阿留申群岛标准时间
    public static final TimeZone US_Arizona = TimeZone.getTimeZone("US/Arizona"); //Mountain 标准时间
    public static final TimeZone US_Central = TimeZone.getTimeZone("US/Central"); //中央标准时间
    public static final TimeZone US_East_Indiana = TimeZone.getTimeZone("US/East-Indiana"); //东部标准时间
    public static final TimeZone US_Eastern = TimeZone.getTimeZone("US/Eastern"); //东部标准时间
    public static final TimeZone US_Hawaii = TimeZone.getTimeZone("US/Hawaii"); //夏威夷标准时间
    public static final TimeZone US_Indiana_Starke = TimeZone.getTimeZone("US/Indiana-Starke"); //中央标准时间
    public static final TimeZone US_Michigan = TimeZone.getTimeZone("US/Michigan"); //东部标准时间
    public static final TimeZone US_Mountain = TimeZone.getTimeZone("US/Mountain"); //Mountain 标准时间
    public static final TimeZone US_Pacific = TimeZone.getTimeZone("US/Pacific"); //太平洋标准时间
    public static final TimeZone US_Pacific_New = TimeZone.getTimeZone("US/Pacific-New"); //太平洋标准时间
    public static final TimeZone US_Samoa = TimeZone.getTimeZone("US/Samoa"); //萨摩亚群岛标准时间
    public static final TimeZone UTC = TimeZone.getTimeZone("UTC"); //协调世界时间
    public static final TimeZone VST = TimeZone.getTimeZone("VST"); //印度支那时间
    public static final TimeZone W_SU = TimeZone.getTimeZone("W-SU"); //莫斯科标准时间
    public static final TimeZone WET = TimeZone.getTimeZone("WET"); //西欧时间
    public static final TimeZone Zulu = TimeZone.getTimeZone("Zulu"); //协调世界时间

    /**
     * Get target locale time.
     * @param time "from" locale time
     * @param from original locale
     * @param to target locale
     * @return "to" locale time
     */
    public static Date getTimeZoneDate(Date time, TimeZone from, TimeZone to) {
        return new Date(time.getTime() + to.getRawOffset() - from.getRawOffset());
    }
}
